{
 "title": "TPLink EasySmartSwitch Stats",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "host",
    "query": "label_values(tplinkexporter_portstats_state, host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Port Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tplinkexporter_portstats_state{host=\"$host\"}",
     "legendFormat": "port {{portnum}}"
    }
   ]
  },
  {
   "title": "Port Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tplinkexporter_portstats_linkstatus{host=\"$host\"}",
     "legendFormat": "port {{portnum}}"
    }
   ]
  },
  {
   "title": "Port Link Status",
   "type": "graph",
   "description": "6 = 1000MF\n5 = 100MF\n4 = 100MH",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tplinkexporter_portstats_linkstatus{host=\"$host\"} !=0",
     "legendFormat": "port {{portnum}}"
    }
   ]
  },
  {
   "title": "good pkt counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tplinkexporter_portstats_rxgoodpkt{host=\"$host\"}[10s])",
     "legendFormat": "RX port {{portnum}}"
    },
    {
     "expr": "rate(tplinkexporter_portstats_txgoodpkt{host=\"$host\"}[10s])",
     "legendFormat": "TX port {{portnum}}"
    }
   ]
  },
  {
   "title": "bad pkt counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(tplinkexporter_portstats_rxbadpkt{host=\"$host\"}[10s])",
     "legendFormat": "RX port {{portnum}}"
    },
    {
     "expr": "rate(tplinkexporter_portstats_txbadpkt{host=\"$host\"}[10s])",
     "legendFormat": "TX port {{portnum}}"
    }
   ]
  }
 ]
}